version: '3'
services:
  demo-app:
    build:
      context: .
    ports:
      - "8100:8080"
    environment:
      - OTEL_SERVICE_NAME=otel-invoke-demo
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"